name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "*"

jobs:
  test_on_windows:
    name: Test Ignition on Windows with Node 14
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests in examples
        run: yarn test:examples

  test_on_macos:
    name: Test Ignition on MacOS with Node 14
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests in examples
        run: yarn test:examples

  test_on_linux:
    name: Test Ignition on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run tests in examples
        run: yarn test:examples
